<a href="https://colab.research.google.com/github/MuskanJainjain/College-Assignment-Foundation-of-Data-Science/blob/main/numpy.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

**Question 01**

In [ ]:
import numpy as np
print(np.__version__)

1.25.2


**Question 02**

In [ ]:
import numpy as np
x = np.array([1,2,3,4])
print("original array:")
print(x)
print("check whether none of the elements of the said array is zero:")
print(np.all(x))
x = np.array([0,1,2,3])
print("original array:")
print(x)
print("check whether none of the elements of the said array is zero:")
print(np.all(x))


original array:
[1 2 3 4]
check whether none of the elements of the said array is zero:
True
original array:
[0 1 2 3]
check whether none of the elements of the said array is zero:
False


**Question 03**

In [ ]:
a1 = np.array([3,5,4,6])
a2 = np.array([7,4,9,4])
print("a1 : ",a1)
print("a2 : ",a2)

print("a1 >= a2")
print(np.greater(a1,a2))


a1 :  [3 5 4 6]
a2 :  [7 4 9 4]
a1 >= a2
[False  True False  True]


**Question-4**

In [ ]:
a1 = np.array([11,4,9,6])
a2 = np.array([9,10,8,6])

print("a1 : ",a1)
print("a2 : ",a2)

print("a1 > a2")
print("a1 >= a2")
print("a1 < a2")
print("a1 <= a2")
print(np.greater(a1,a2))
print(np.greater_equal(a1,a2))
print(np.less(a1,a2))
print(np.less_equal(a1,a2))

a1 :  [11  4  9  6]
a2 :  [ 9 10  8  6]
a1 > a2
a1 >= a2
a1 < a2
a1 <= a2
[ True False  True False]
[ True False  True  True]
[False  True False False]
[False  True False  True]


**Question 5**

In [ ]:
x = np.array([1,7,13,105])
print(x.size)
print(x)
print(x.dtype)

print("size of the memory occupied by the said array:")
print(x.itemsize * x.size)

4
[  1   7  13 105]
int64
size of the memory occupied by the said array:
32


**Question 6**

In [ ]:
import numpy as np
array = np.arange(30,71)

print("array of the integers from 30 to 70")
print(array)

array of the integers from 30 to 70
[30 31 32 33 34 35 36 37 38 39 40 41 42 43 44 45 46 47 48 49 50 51 52 53
 54 55 56 57 58 59 60 61 62 63 64 65 66 67 68 69 70]


**Question 7**

In [ ]:
import numpy as np
array = np.arange(30,71,2)

print("array of the even integers from 30 to 70")
print(array)

array of the even integers from 30 to 70
[30 32 34 36 38 40 42 44 46 48 50 52 54 56 58 60 62 64 66 68 70]


**Question 8**

In [ ]:
import numpy as np
array_2D = np.identity(3)

print('3*3 matrix:')
print(array_2D)

3*3 matrix:
[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


**Question 9**

In [ ]:
import numpy as np
a = np.arange(10,22).reshape((3, 4))
print("Original array:")
print(a)
print("Each element of the array is:")
for x in np.nditer(a):
  print(x,end="")

Original array:
[[10 11 12 13]
 [14 15 16 17]
 [18 19 20 21]]
Each element of the array is:
101112131415161718192021